AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: CloudMart Product Customer and Order API

Parameters:

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:

  ProductApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        !Sub CloudMart-Product-API-${Environment}

      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      CodeUri: ../../src/product/
      MemorySize: 256
      Timeout: 30

      Role:
        Fn::ImportValue:
          !Sub CloudMart-LambdaExecutionRoleArn-${Environment}

      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue:
              !Sub CloudMart-Lambda-SG-ID

        SubnetIds:
          - Fn::ImportValue:
              !Sub CloudMart-Private-Subnet-ID

          - Fn::ImportValue:
              !Sub CloudMart-Private-Subnet-2-ID

      Environment:
        Variables:
          ENVIRONMENT:
            !Ref Environment

          DATABASE_SECRET_ARN:
            Fn::ImportValue:
              CloudMart-DatabaseSecretArn

      Events:

        GetProducts:
          Type: Api
          Properties:
            RestApiId:
              !Ref ProductApi
            Path: /product
            Method: GET

        CreateProduct:
          Type: Api
          Properties:
            RestApiId:
              !Ref ProductApi
            Path: /product
            Method: POST

        GetProduct:
          Type: Api
          Properties:
            RestApiId:
              !Ref ProductApi
            Path: /product/{id}
            Method: GET

        UpdateProduct:
          Type: Api
          Properties:
            RestApiId:
              !Ref ProductApi
            Path: /product/{id}
            Method: PUT

        DeleteProduct:
          Type: Api
          Properties:
            RestApiId:
              !Ref ProductApi
            Path: /product/{id}
            Method: DELETE


  OrderApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        !Sub CloudMart-Order-API-${Environment}

      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      CodeUri: ../../src/order/
      MemorySize: 256
      Timeout: 30

      Role:
        Fn::ImportValue:
          !Sub CloudMart-LambdaExecutionRoleArn-${Environment}

      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue:
              !Sub CloudMart-Lambda-SG-ID

        SubnetIds:
          - Fn::ImportValue:
              !Sub CloudMart-Private-Subnet-ID

          - Fn::ImportValue:
              !Sub CloudMart-Private-Subnet-2-ID

      Environment:
        Variables:
          ENVIRONMENT:
            !Ref Environment

          DATABASE_SECRET_ARN:
            Fn::ImportValue:
              CloudMart-DatabaseSecretArn

      Events:

        CreateCustomer:
          Type: Api
          Properties:
            RestApiId:
              !Ref ProductApi
            Path: /customer
            Method: POST

        GetCustomers:
          Type: Api
          Properties:
            RestApiId:
              !Ref ProductApi
            Path: /customer
            Method: GET

        GetCustomer:
          Type: Api
          Properties:
            RestApiId:
              !Ref ProductApi
            Path: /customer/{id}
            Method: GET

        UpdateCustomer:
          Type: Api
          Properties:
            RestApiId:
              !Ref ProductApi
            Path: /customer/{id}
            Method: PUT

        DeleteCustomer:
          Type: Api
          Properties:
            RestApiId:
              !Ref ProductApi
            Path: /customer/{id}
            Method: DELETE

        CreateOrder:
          Type: Api
          Properties:
            RestApiId:
              !Ref ProductApi
            Path: /order
            Method: POST

        GetOrders:
          Type: Api
          Properties:
            RestApiId:
              !Ref ProductApi
            Path: /order
            Method: GET

        GetOrder:
          Type: Api
          Properties:
            RestApiId:
              !Ref ProductApi
            Path: /order/{id}
            Method: GET

        UpdateOrder:
          Type: Api
          Properties:
            RestApiId:
              !Ref ProductApi
            Path: /order/{id}
            Method: PUT

        DeleteOrder:
          Type: Api
          Properties:
            RestApiId:
              !Ref ProductApi
            Path: /order/{id}
            Method: DELETE


  ProductApi:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        !Sub CloudMart-Product-Customer-Order-API-${Environment}

      StageName:
        !Ref Environment

      EndpointConfiguration:
        Type: REGIONAL

      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

      Auth:
        DefaultAuthorizer: CloudMartAuthorizer

        Authorizers:

          CloudMartAuthorizer:
            FunctionArn:
              Fn::ImportValue:
                !Sub CloudMart-Lambda-Authorizer-Arn-${Environment}

            FunctionPayloadType: REQUEST

            Identity:
              Headers:
                - Authorization

            AuthorizerResultTtlInSeconds: 0


Outputs:

  ProductApiUrl:
    Description: CloudMart API URL

    Value:
      !Sub
        - https://${ApiId}.execute-api.${AWS::Region}.amazonaws.com/${Environment}
        - ApiId:
            !Ref ProductApi


  ProductApiFunctionArn:
    Description: CloudMart Product Lambda ARN

    Value:
      !GetAtt ProductApiFunction.Arn

    Export:
      Name:
        !Sub CloudMart-Product-Api-Lambda-Arn-${Environment}


  ProductApiFunctionName:
    Description: CloudMart Product Lambda name

    Value:
      !Ref ProductApiFunction

    Export:
      Name:
        !Sub CloudMart-Product-Api-Lambda-Name-${Environment}


  OrderApiFunctionArn:
    Description: CloudMart Order and Customer Lambda ARN

    Value:
      !GetAtt OrderApiFunction.Arn

    Export:
      Name:
        !Sub CloudMart-Order-Api-Lambda-Arn-${Environment}


  OrderApiFunctionName:
    Description: CloudMart Order and Customer Lambda name

    Value:
      !Ref OrderApiFunction

    Export:
      Name:
        !Sub CloudMart-Order-Api-Lambda-Name-${Environment}