AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: CloudMart Authentication Stack

# ==========================================================
# PARAMETERS
# ==========================================================

Parameters:

  Environment:
    Type: String
    AllowedValues:
      - dev
      - test
      - prod
    Description: Deployment environment


# ==========================================================
# RESOURCES
# ==========================================================

Resources:

  # ========================================================
  # LAMBDA AUTHORIZER
  # ========================================================

  LambdaAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub cloudmart-${Environment}-lambda-authorizer
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      CodeUri: ../../src/authorizer/
      MemorySize: 128
      Timeout: 10
      Role:
        Fn::ImportValue: !Sub cloudmart-${Environment}-lambda-authorizer-role-arn
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub cloudmart-${Environment}-lambda-sg-id
        SubnetIds:
          - Fn::ImportValue: !Sub cloudmart-${Environment}-private-subnet-1-id
          - Fn::ImportValue: !Sub cloudmart-${Environment}-private-subnet-2-id
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
      Tags:
        Project: CloudMart
        Environment: !Ref Environment
        Component: Authentication


  # ========================================================
  # INIT SCHEMA LAMBDA
  # ========================================================

  InitSchemaLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub cloudmart-${Environment}-initschema
      CodeUri: ../../src/init-schema/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Timeout: 300
      MemorySize: 256
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub cloudmart-${Environment}-lambda-sg-id
        SubnetIds:
          - Fn::ImportValue: !Sub cloudmart-${Environment}-private-subnet-1-id
          - Fn::ImportValue: !Sub cloudmart-${Environment}-private-subnet-2-id
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameters
                - ssm:GetParameter
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/app/${Environment}/database/*"
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
      Tags:
        Project: CloudMart
        Environment: !Ref Environment
        Component: Database


# ==========================================================
# OUTPUTS
# ==========================================================

Outputs:

  LambdaAuthorizerArn:
    Description: ARN of the CloudMart Lambda Authorizer
    Value: !GetAtt LambdaAuthorizer.Arn
    Export:
      Name: !Sub cloudmart-${Environment}-lambda-authorizer-arn

  LambdaAuthorizerName:
    Description: Name of the CloudMart Lambda Authorizer
    Value: !Ref LambdaAuthorizer
    Export:
      Name: !Sub cloudmart-${Environment}-lambda-authorizer-name

  InitSchemaLambdaArn:
    Description: ARN of the Schema Initialization Lambda
    Value: !GetAtt InitSchemaLambda.Arn
    Export:
      Name: !Sub cloudmart-${Environment}-initschema-lambda-arn

  InitSchemaLambdaName:
    Description: Name of the Schema Initialization Lambda
    Value: !Ref InitSchemaLambda
    Export:
      Name: !Sub cloudmart-${Environment}-initschema-lambda-name