AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: CloudMart Authentication Stack


# ==========================================================
# PARAMETERS
# ==========================================================

Parameters:

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Deployment environment


# ==========================================================
# RESOURCES
# ==========================================================

Resources:

  # ========================================================
  # LAMBDA AUTHORIZER
  # ========================================================

  LambdaAuthorizer:

    Type: AWS::Serverless::Function

    Properties:

      FunctionName:
        !Sub CloudMart-Lambda-Authorizer-${Environment}

      Runtime: python3.12

      Handler: lambda_function.lambda_handler

      CodeUri: ../../src/authorizer/

      # ====================================================
      # IAM ROLE
      # Import role created by IAM stack
      # ====================================================

      Role:
        Fn::ImportValue:
          !Sub CloudMart-LambdaAuthorizerRoleArn-${Environment}

      MemorySize: 128

      Timeout: 10

      # ====================================================
      # ENVIRONMENT VARIABLES
      # ====================================================

      Environment:

        Variables:

          ENVIRONMENT:
            !Ref Environment

      # ====================================================
      # NO VPC CONFIGURATION
      #
      # The Authorizer does not need to access RDS.
      # API Gateway can invoke it without VPC configuration.
      # ====================================================

      Tags:

        Project:
          CloudMart

        Environment:
          !Ref Environment

        Component:
          Authentication


# ==========================================================
# OUTPUTS
# ==========================================================

Outputs:

  # ========================================================
  # LAMBDA AUTHORIZE ARN
  # ========================================================

  LambdaAuthorizerArn:

    Description:
      ARN of the CloudMart Lambda Authorizer

    Value:
      !GetAtt LambdaAuthorizer.Arn

    Export:

      Name:
        !Sub CloudMart-Lambda-Authorizer-Arn-${Environment}


  # ========================================================
  # LAMBDA AUTHORIZE NAME
  # ========================================================

  LambdaAuthorizerName:

    Description:
      Name of the CloudMart Lambda Authorizer

    Value:
      !Ref LambdaAuthorizer

    Export:

      Name:
        !Sub CloudMart-Lambda-Authorizer-Name-${Environment}