AWSTemplateFormatVersion: '2010-09-09'

Description: CloudMart Event Driven Low Stock Alert Stack

Parameters:

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

  LowStockEmail:
    Type: String


Resources:

  LowStockTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub cloudmart-${Environment}-low-stock-alerts
      DisplayName: !Sub CloudMart ${Environment} Low Stock Alerts


  LowStockEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref LowStockTopic
      Protocol: email
      Endpoint: !Ref LowStockEmail


  CloudMartEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub cloudmart-${Environment}-event-bus


  LowStockEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub cloudmart-${Environment}-low-stock-rule
      EventBusName: !Ref CloudMartEventBus
      State: ENABLED

      EventPattern:
        source:
          - cloudmart.product
        detail-type:
          - Low Stock Alert

      Targets:
        - Id: LowStockSNSTarget
          Arn: !Ref LowStockTopic


  LowStockSNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref LowStockTopic

      PolicyDocument:
        Version: '2012-10-17'

        Statement:
          - Sid: AllowEventBridgePublish
            Effect: Allow

            Principal:
              Service:
                - events.amazonaws.com

            Action:
              - sns:Publish

            Resource:
              !Ref LowStockTopic


Outputs:

  LowStockTopicArn:
    Value: !Ref LowStockTopic
    Export:
      Name: !Sub CloudMart-${Environment}-LowStockTopicArn


  CloudMartEventBusArn:
    Value: !GetAtt CloudMartEventBus.Arn
    Export:
      Name: !Sub CloudMart-${Environment}-EventBusArn


  CloudMartEventBusName:
    Value: !Ref CloudMartEventBus
    Export:
      Name: !Sub CloudMart-${Environment}-EventBusName