name: CloudMart Auth Stack Test

on:
  push:
    branches:
      - authorizer

env:
  AWS_REGION: ap-south-1
  STACK_NAME: cloudmart-auth

permissions:
  id-token: write
  contents: read

jobs:

  test-and-deploy:

    name: Test and Deploy Auth Stack

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity

      - name: Install SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Validate Auth Stack
        run: |
          sam validate \
            --template-file infrastructure/cloudformation/auth-stack.yml

      - name: Build Auth Stack
        run: |
          sam build \
            --template-file infrastructure/cloudformation/auth-stack.yml

      - name: Deploy Auth Stack
        run: |
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name $STACK_NAME \
            --region $AWS_REGION \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset

      - name: Display Auth Stack Outputs
        run: |
          aws cloudformation describe-stacks \
            --stack-name $STACK_NAME \
            --query 'Stacks[0].Outputs' \
            --output table

      - name: Test Lambda Authorizer
        run: |
          aws lambda get-function \
            --function-name CloudMart-Lambda-Authorizer-dev

      - name: Deployment Successful
        run: |
          echo "Auth Stack deployed successfully."